services:
  - type: web
    name: uyjoy-ml-form
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.ml
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DASHBOARD_USERNAME
        sync: false
      - key: DASHBOARD_PASSWORD
        sync: false

  - type: web
    name: uyjoy-metabase
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.metabase
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: MB_JETTY_PORT
        value: "10000"
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx430m"
      - key: MB_DB_CONNECTION_URI
        sync: false
