services:
  - type: web
    name: uyjoy-ml-form
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.ml
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DASHBOARD_USERNAME
        sync: false
      - key: DASHBOARD_PASSWORD
        sync: false

  - type: web
    name: uyjoy-metabase
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.metabase
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: MB_JETTY_PORT
        value: "10000"
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx300m -XX:+UseSerialGC"
      - key: MB_JETTY_MAXTHREADS
        value: "20"
      - key: MB_JETTY_MINTHREADS
        value: "2"
      - key: MB_DB_CONNECTION_POOL_MAX_SIZE
        value: "3"
      - key: MB_ANON_TRACKING_ENABLED
        value: "false"
      - key: MB_SEND_ANONYMOUS_USAGE_STATS
        value: "false"
      - key: MB_CHECK_FOR_UPDATES
        value: "false"
      - key: MB_DB_CONNECTION_URI
        sync: false
